### ISSUE TITLE
ERROR: parse :///id//: missing protocol scheme when logging into OEM Orgs

### ISSUE THREAD

**Issue by mmalamud** [heroku/force#144]
I can login fine into my regular org but when trying to connect to for example 

cloudaware-2323.cloudforce.com, I get an error. 

turbo:Downloads mmalamud$ ./force login -u=xxx@xxxx.com -p=xxxx
Save login was  ok
ERROR: parse :///id//: missing protocol scheme

**Comment by dcarroll** [comment]
can you try adding the -i flag
./force login -u=xxx@xxx.com -p=xxx -i=cloudaware-2323.cloudforce.com

**Comment by daidaihuhu** [comment]
Dear dcarroll, I have the same issue as mmalamud, and still got the warning even I added the -i term.

xxx$ force login -i=ap2.salesforce.com -u=xxx@xxx.com -p=xxxx
Loaded Endpoint: (https://ap2.salesforce.com)
Save login was  ok
ERROR: parse :///id//: missing protocol scheme

**Comment by dcarroll** [comment]
What happens when you login using the web interface?

Try:

force login<return>

On Sat, Jul 25, 2015 at 6:52 AM, daidaihuhu <notifications@github.com>
wrote:

> Dear dcarroll, I have the same issue as mmalamud, and still got the
> warning even I added the -i term.
>
> xxx$ force login -i=ap2.salesforce.com -u=xxx@xxx.com -p=xxxx
> Loaded Endpoint: (https://ap2.salesforce.com)
> Save login was ok
> ERROR: parse :///id//: missing protocol scheme
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/144#issuecomment-124848769>.
>



-- 
Thanks,
Dave

**Comment by daidaihuhu** [comment]
Dear Dave,

Thank you for your reply. I think the reason was I have no enough API
function in my account. I use a free trial account, which is professional
edition.

I will try to pursue my company to buy a enterprise edition account, so
that I can try again.

Thanks!

Max

**Comment by dcarroll** [comment]
Sign up for a developer edition.

https://developer.salesforce.com/signup?d=70130000000td6N

Free, and as capable as an Enterprise Edition.

Dave Carroll

On Aug 5, 2015, at 5:37 PM, daidaihuhu <notifications@github.com> wrote:

Dear Dave,

Thank you for your reply. I think the reason was I have no enough API
function in my account. I use a free trial account, which is professional
edition.

I will try to pursue my company to buy a enterprise edition account, so
that I can try again.

Thanks!

Max

On Thu, Aug 6, 2015 at 2:07 AM, Dave Carroll <notifications@github.com>
wrote:

> What happens when you login using the web interface?
>
> Try:
>
> force login<return>
>
> On Sat, Jul 25, 2015 at 6:52 AM, daidaihuhu <notifications@github.com>
> wrote:
>
> > Dear dcarroll, I have the same issue as mmalamud, and still got the
> > warning even I added the -i term.
> >
> > xxx$ force login -i=ap2.salesforce.com -u=xxx@xxx.com -p=xxxx
> > Loaded Endpoint: (https://ap2.salesforce.com)
> > Save login was ok
> > ERROR: parse :///id//: missing protocol scheme
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/heroku/force/issues/144#issuecomment-124848769>.
> >
>
>
>
> --
> Thanks,
> Dave
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/144#issuecomment-128052120>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/heroku/force/issues/144#issuecomment-128194137>.

**Comment by daidaihuhu** [comment]
Thank you, Dave. I'll try.

Max

**Comment by darrenatyurgosky** [comment]
This error happened to me, I changed my password to alphanumeric-only and force login worked.

**Comment by adamlincoln** [comment]
An ampersand in password causes this error.

**Comment by floyd-may** [comment]
No ampersands in my password yet still getting this error.
