### ISSUE TITLE
Error (crash) on 'force fetch -t aura -d .' on 64-bit Windows

### ISSUE THREAD

**Issue by rrcook** [heroku/force#145]
64-bit Windows, using pre-compiled binary from here.
I'm able to login to my individual dev org, fine, but when trying to get my Lightning components with
force fetch -t aura -d .
I get the error below.
The same command is successful using 64-bit Linux from the pre-compiled binary

c:\projects\ltest\expenses>force fetch -t aura -d .
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x0 pc=0x41ca3e]

goroutine 16 [running]:
runtime.panic(0x7f5ba0, 0xaa3fe2)
        /tmp/build_f8ba0f4168b936fea1eb59aef85c032b/go/src/pkg/runtime/panic.c:279 +0x11f
main.(*Force).GetAuraBundlesList(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /app/vendor/lib/go/src/src/github.com/heroku/force/force.go:440 +0x2ae
main.(*Force).GetAuraBundles(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /app/vendor/lib/go/src/src/github.com/heroku/force/force.go:421 +0x81
main.runFetchAura2(0xaa26e0, 0x8406f0, 0x0)
        /app/vendor/lib/go/src/src/github.com/heroku/force/fetch.go:84 +0x85
main.runFetch(0xaa26e0, 0xc082012240, 0x0, 0x0)
        /app/vendor/lib/go/src/src/github.com/heroku/force/fetch.go:199 +0x1a67
main.main()
        /app/vendor/lib/go/src/src/github.com/heroku/force/main.go:49 +0x2b1

goroutine 19 [finalizer wait]:
runtime.park(0x46eb90, 0xaa8fa8, 0xaa7089)
        /tmp/build_f8ba0f4168b936fea1eb59aef85c032b/go/src/pkg/runtime/proc.c:1369 +0xac
runtime.parkunlock(0xaa8fa8, 0xaa7089)
        /tmp/build_f8ba0f4168b936fea1eb59aef85c032b/go/src/pkg/runtime/proc.c:1385 +0x42
runfinq()
        /tmp/build_f8ba0f4168b936fea1eb59aef85c032b/go/src/pkg/runtime/mgc0.c:2644 +0xdd
runtime.goexit()
        /tmp/build_f8ba0f4168b936fea1eb59aef85c032b/go/src/pkg/runtime/proc.c:1445

**Comment by dcarroll** [comment]
I am unable to reproduce this. Can you tell me your version of force?

run ` force version `

And windows version

run ` ver `

**Comment by rrcook** [comment]
c:\Users\rrcook\bin>force version
v0.22.19

c:\Users\rrcook\bin>ver

Microsoft Windows [Version 6.1.7601]
(Windows 7 Enterprise, Service Pack 1)

**Comment by rrcook** [comment]
...And today it is working. No idea what the difference would be. I'll close this for now, thank you for trying it.
