### ISSUE TITLE
No help for force fetch type

### ISSUE THREAD

**Issue by fstrevisanK2** [heroku/force#148]
Should be great to get quick help on what types are supported and how to spell them. Probably add something to force help fetch.

**Comment by dcarroll** [comment]
There is a `force descibe` that lists out metadata and a `force describe
<metadata>` for more details.

On Tue, Mar 17, 2015 at 6:23 AM, Fernando da Silva Trevisan <
notifications@github.com> wrote:

> Should be great to get quick help on what types are supported and how to
> spell them. Probably add something to force help fetch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/148>.
>



-- 
Thanks,
Dave

**Comment by fstrevisanK2** [comment]
Dave, thanks a lot for the quick answer! But :
./force describe metadata
Shows:
ERROR: You must specify metadata or sobject for description
example: force describe metadata
and also:
./force describe
ERROR: You must specify metadata or sobject for description
example: force describe metadata

**Comment by dcarroll** [comment]
Sorry, the help is wrong.

Try
`force describe -t metadata`

or

`force describe -t metadata -n EmailTemplate`


On Tue, Mar 17, 2015 at 10:46 AM, Fernando da Silva Trevisan <
notifications@github.com> wrote:

> Dave, thanks a lot for the quick answer! But :
> ./force describe metadata
> Shows:
> ERROR: You must specify metadata or sobject for description
> example: force describe metadata
> and also:
> ./force describe
> ERROR: You must specify metadata or sobject for description
> example: force describe metadata
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/148#issuecomment-82495564>.
>



-- 
Thanks,
Dave

**Comment by fstrevisanK2** [comment]
GREAT, that worked. And confirmed the other issue I've opened... no EmailTemplate on export/fetch :(

Thanks a lot, Dave!

**Comment by mukeshietk101** [comment]
that works or me. Saved my hours.
force describe -t sobject -n=Merchandise__c
