### ISSUE TITLE
No email templates on the export or fetch

### ISSUE THREAD

**Issue by fstrevisanK2** [heroku/force#149]
After doing an export, I can't find any email templates on the generated dir.

When I do a fetch, there's no type matching the email templates. I've tried to find it in the source code, and the export do have a "EmailTemplate" node (so to speak) but on fetch, there are commented code about it.

**Comment by fstrevisanK2** [comment]
Adding info, using this:
./force fetch -t EmailTemplate -n nameOfEmailTemplate
returns this:
ERROR: Could not find any objects for EmailTemplate. (Is the metadata type correct?)

**Comment by dcarroll** [comment]
I wrote a shell script and it does

`force query "Select DeveloperName From EmailTemplate Where Folder.Name =
'MktComms'"
force fetch -t EmailTemplate -n MktComms/nameOfEmailTemplate
`


On Tue, Mar 17, 2015 at 11:07 AM, Fernando da Silva Trevisan <
notifications@github.com> wrote:

> Adding info, using this:
> ./force fetch -t EmailTemplate -n nameOfEmailTemplate
> returns this:
> ERROR: Could not find any objects for EmailTemplate. (Is the metadata type
> correct?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/149#issuecomment-82503906>.
>



-- 
Thanks,
Dave

**Comment by fstrevisanK2** [comment]
Dave, amazing! Using the folder name I was able to download the email template. Thanks a lot!

**Comment by dcarroll** [comment]
Sorry, for the lack of documentation, I'm pretty much doing this by myself
and sometimes can't get to the doc, or my likely, a new squirrel runs by!

On Tue, Mar 17, 2015 at 11:25 AM, Fernando da Silva Trevisan <
notifications@github.com> wrote:

> Closed #149 <https://github.com/heroku/force/issues/149>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/149#event-257228687>.
>



-- 
Thanks,
Dave
