### ISSUE TITLE
force field create ... fields not getting created

### ISSUE THREAD

**Issue by babakh** [heroku/force#163]
Hi,
I am running the following to create an object and a set of fields:
force sobject create LogSettings
force field   create LogSettings__c  Logger:picklist picklist:"Custom Object, Endpoint"
force field   create LogSettings__c  Enabled:checkbox
force field   create LogSettings__c  "Object Name":textarea
force field   create LogSettings__c  Endpoint:textarea

When I list the fields in the object (force field list logSettings__c), I get the following:
CreatedById: reference (User)
CreatedDate: datetime
Id: id
IsDeleted: boolean
LastModifiedById: reference (User)
LastModifiedDate: datetime
Name: string
OwnerId: reference (Group, User)
SystemModstamp: datetime

When I try to reference one of the fields, I get the following:
ERROR: Invalid field Logger__c for SObject LogSettings__c

Ironically, the fields show up in Salesforce when I pull up the custom object.

I am running v0.22.25.  Any ideas?

Thanks!

**Comment by dcarroll** [comment]
This may be due to lack of visibility for the profile. In other words, when the field is created the default visibility is NOT visible.  Check the profile to see the visibility of the newly created fields.
