### ISSUE TITLE
force login i=test u=username p=password just hangs on 64-bit Linux

### ISSUE THREAD

**Issue by jbgene** [heroku/force#167]
I copied the pre-compiled 64-bit Linux version of force to a 64-bit linux server. "force help" works so it runs but force login i=test u=username p=password doesn't.

**Comment by dcarroll** [comment]
Test doesn't mean anything to the CLI. Use the full sandbox url.

Dave Carroll

On May 1, 2015, at 4:51 PM, jbgene <notifications@github.com> wrote:

I copied the pre-compiled 64-bit Linux version of force to a server. "force
help" works so it runs but force login i=test u=username p=password doesn't.

—
Reply to this email directly or view it on GitHub
<https://github.com/heroku/force/issues/167>.
