### ISSUE TITLE
Escaping issue for the password

### ISSUE THREAD

**Issue by cloudconversion** [heroku/force#174]
If the Salesforce password contains a $, the force login with -u -p results in "ERROR: INVALID_LOGIN: Invalid username, password, security token; or user locked out.".  

For example:
force login -u jon@cloudconversion.com -p test12348$yvz4VQFVVvGJvVWFaMtzc7QV7
would fail with this INVALID_LOGIN error.

However, if you remove the $ from the password and use the new security token, then the login is successful.

**Comment by cwarden** [comment]
Your shell is expanding the variable, `yvz4VQFVVvGJvVWFaMtzc7QV7`.  Quote your password to prevent shell expansion, `force login -u jon@cloudconversion.com -p 'test12348$yvz4VQFVVvGJvVWFaMtzc7QV7'`
