### ISSUE TITLE
Accept "src" as a valid metadata directory

### ISSUE THREAD

**Issue by boxfoot** [heroku/force#176]
Documentation & built-in help says that either "src" or "metadata" is a valid directory name for the push command, but metadata is the only value that is actually accepted.

Looks like it might be as simple as un-commenting `config.go` line 15 (https://github.com/heroku/force/blob/master/config.go#L15)

**Comment by dcarroll** [comment]
I'll open a bug on the documentation and built in help.  Metadata dir reflects what comes in the package from Force.com when metadata is retrieved.

**Comment by boxfoot** [comment]
Thanks.   My use case is that I actually mostly use other tools (in the case, MavensMate) but wanted to push a specific metadata object that I was having trouble deploying through that tool.  I ended up co

**Comment by boxfoot** [comment]
Oops - that was a mistake.

**Comment by dcarroll** [comment]
The issue with the "src" directory being a possible metadata root directory comes from one of the original authors. In the Eclipse plugin, all metadata is place under a "src" folder.  In reality the metadata API delivers a zip file and all the metadata is rooted to a "metadata" folder.  Having to root folders is confusing, so I am removing the documentation that refers to "src".

**Comment by dshahin** [comment]
The precompiled binary for Mac gives an error that seems to indicate that "src" is still an acceptable option.   Is it possible to specify "src" as an acceptable directory via a command line argument or an environment variable?

ERROR: Current directory does not contain a metadata or src directory

**Comment by ViViDboarder** [comment]
Does the zip file really include a folder called `metadata` which contains the `package.xml`? The documentation and my prior experience is that the root of the zip file includes the `package.xml` and that it could be extracted to wherever.

That aside, what is the downside to supporting other, long standing, conventions? Many teams have engineers using Eclipse still as it is still the only supported IDE by Salesforce. This is the only tool that does not support `src`.

**Comment by cwarden** [comment]
fwiw, creating a symlink from `metadata` to `src` is a simple work-around.

**Comment by dcarroll** [comment]
I am still looking at this issue.  Unfortunately the effects of this run pretty deep as there is other logic and dependencies that assume the current "metadata" folder.

**Comment by ViViDboarder** [comment]
Is there still hard coded references to the metadata folder? Everywhere "metadata" is referenced directly could (and probably should) be replaced with the existing `GetSrcDir()` function.

That would allow flexibility and backwards compatible support with Eclipse users. My team does not all use `force`.

This issue has kept me from using master directly and instead using a private fork. It would be nice to be on mainline again and make it easier for me to commit changes upstream.

**Comment by dcarroll** [comment]
Ok, that feels like a serious vote to have this implemented.  @ViViDboarder, if you have this solved in your fork, and is fully tested, go ahead and create a PR.

**Comment by ViViDboarder** [comment]
Ok. I'll work on cleaning it up next week.

>
