### ISSUE TITLE
"force fetch" creates an extra nested folder

### ISSUE THREAD

**Issue by nelsonra** [heroku/force#178]
There seems to be some strange behaviour when I use "force fetch -t aura -d". I see that it creates a folder with in a folder. I'm using OS X 10.

Example 1 (no added folder) : Fetch lightning / aura resources with no src folder in my folder structure
- Folder structure
-- /Development/test/ (empty folder)
- run : force fetch -t aura -d ./src
- new folder structure
-- /Development/test/src/metadata/aura

Example 2 (added folder) : Fetch lightning / aura resources with src folder in my folder structure
- Folder structure
-- /Development/test/src
- run : force fetch -t aura -d ./src
- new folder structure
-- /Development/test/src/src/metadata/aura

Example 3 (no added folder) : Fetch lightning / aura resources with full folder path
- Folder structure
-- /Development/test/src
- run : force fetch -t aura -d /Development/test/src
- folder structure stays the same
-- /Development/test/src/metadata/aura

Also for me I was expecting that if i'm downloading aura resources and specify the target directory that I don't get the metadata folder either. Why is the metadata folder pulled down if I specify the type of resource?

**Comment by dcarroll** [comment]
I see the behavior with creating the extra folder.  It will also create and
extra folder with this syntax:

force fetch -t aura -d newfolder

So there is a bug here. I'll check it out unless you have done the fix.

On Thu, Jun 25, 2015 at 2:26 AM, Nelson Ramalho <notifications@github.com>
wrote:

> There seems to be some strange behaviour when I use "force fetch -t aura
> -d". I see that it creates a folder with in a folder. I'm using OS X 10.
>
> Example 1 (no added folder) : Fetch lightning / aura resources with no src
> folder in my folder structure
>
>    - Folder structure -- /Development/test/ (empty folder)
>    - run : force fetch -t aura -d ./src
>    - new folder structure -- /Development/test/src/metadata/aura
>
> Example 2 (added folder) : Fetch lightning / aura resources with src
> folder in my folder structure
>
>    - Folder structure -- /Development/test/src
>    - run : force fetch -t aura -d ./src
>    - new folder structure -- /Development/test/src/src/metadata/aura
>
> Example 3 (no added folder) : Fetch lightning / aura resources with full
> folder path
>
>    - Folder structure -- /Development/test/src
>    - run : force fetch -t aura -d /Development/test/src
>    - folder structure stays the same --
>    /Development/test/src/metadata/aura
>
> Also for me I was expecting that if i'm downloading aura resources and
> specify the target directory that I don't get the metadata folder either.
> Why is the metadata folder pulled down if I specify the type of resource?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/178>.
>



-- 
Thanks,
Dave
