### ISSUE TITLE
Precompiled binary links seem to be broken

### ISSUE THREAD

**Issue by grekker** [heroku/force#184]
Tried downloading a precompiled binary and got an error message, clicked on the other binary links and I get the same error page for each.

<img width="764" alt="screenshot 2015-07-03 12 31 18" src="https://cloud.githubusercontent.com/assets/131729/8505379/7334b2b4-217f-11e5-8722-6750bd8e72a1.png">

Figured I'd try to compile from source instead, and I received this error:

    omega:go grekker$ go get -u github.com/heroku/force
    # github.com/ddollar/config
    ../../go/src/github.com/ddollar/config/windows.go:8: (*Config).homeDirectory redeclared in this block
    	previous declaration at ../../go/src/github.com/ddollar/config/posix.go:9

Bummer.

**Comment by dcarroll** [comment]
Just rebooted, can you try again?

**Comment by grekker** [comment]
Progress. Sometimes when clicking on the download links I get this error:
<img width="724" alt="screenshot 2015-07-03 15 05 00" src="https://cloud.githubusercontent.com/assets/131729/8505923/5f85f4b0-2195-11e5-9d0d-d53c8491bc4b.png">
<img width="693" alt="screenshot 2015-07-03 15 09 45" src="https://cloud.githubusercontent.com/assets/131729/8505927/9c29810c-2195-11e5-85cc-a3ad9305260e.png">

But most of the time now I get a file. Every binary I download (regardless of platform) is named "force" with no file extension. The 64bit OS X file is 9.4MB. The 64bit Linux one is 9.1MB.

How should I execute the downloaded file?

**Comment by dcarroll** [comment]
For Mac and Linux you need to chmod +x the file. The windows link should
download an exe.

On Fri, Jul 3, 2015 at 6:10 PM, grekker <notifications@github.com> wrote:

> Progress. Sometimes when clicking on the download links I get this error:
> [image: screenshot 2015-07-03 15 05 00]
> <https://cloud.githubusercontent.com/assets/131729/8505923/5f85f4b0-2195-11e5-9d0d-d53c8491bc4b.png>
> [image: screenshot 2015-07-03 15 09 45]
> <https://cloud.githubusercontent.com/assets/131729/8505927/9c29810c-2195-11e5-85cc-a3ad9305260e.png>
>
> But most of the time now I get a file. Every binary I download (regardless
> of platform) is named "force" with no file extension. The 64bit OS X file
> is 9.4MB. The 64bit Linux one is 9.1MB.
>
> How should I execute the downloaded file?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/184#issuecomment-118447492>.
>



-- 
Thanks,
Dave

**Comment by duncanfinney** [comment]
The error is because the ddollar/config dependency doesn't compile with golang v1.4

**Comment by timjrobinson** [comment]
I'm still frequently getting 503 and 403 errors download the precompilied binaries. It sometimes works in browser and usually fails with wget. 

```
ubuntu@tim-gce-eu-02-dev:~/newclient$ wget https://godist-new.herokuapp.com/projects/heroku/force/releases/current/linux-amd64/force
--2015-10-12 12:27:06--  https://godist-new.herokuapp.com/projects/heroku/force/releases/current/linux-amd64/force
Resolving godist-new.herokuapp.com (godist-new.herokuapp.com)... 107.21.103.136
Connecting to godist-new.herokuapp.com (godist-new.herokuapp.com)|107.21.103.136|:443... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2015-10-12 12:27:37 ERROR 503: Service Unavailable.
```
