### ISSUE TITLE
force cli can't fully fetch Aura

### ISSUE THREAD

**Issue by megatran** [heroku/force#185]
Hi,

I use force cli with sublime text's lightning plugin to work with the SF Lightning component. Recently, I noticed the plugin can't fully fetch the lightning component anymore. So I tried the command line using force and it could not fully fetch lightning component either.

force fetch -t Aura -n ManagerDashBoard

(ManagerDashBoard is the name of my component and this command line creates metadata\aura\ManagerDashBoard\ and only fetches a file .manifest

In .manifest
{"Name":"ManagerDashBoard","Id":"0Ab110000004CYhCAM","Files":[]}

**Comment by dcarroll** [comment]
Is this still an issue?

**Comment by megatran** [comment]
The issue is gone with the new update!

Thank you Dave
