### ISSUE TITLE
No package.xml found

### ISSUE THREAD

**Issue by chexxor** [heroku/force#186]
```
$ force push -t ApexPage -n MyPage
Validating and deploying push...
Deploying now...

Failures - 1
ERROR with package.xml, line 0
 No package.xml found
The deployment took 7.9953371s to run.
```

Windows 8.1 - force.exe 64-bit

I have my source code in a git repo, I checked it out, renamed "src" to "metadata" (couldn't figure out how to specify source dir), and ran the `force push` command as above.

I can't figure out how this project is intending to manage the package.xml. Any docs on that?

**Comment by dcarroll** [comment]
I have verified that this is a bug for windows only in the current version of the CLI. Likely a path or working directory issue.

**Comment by chexxor** [comment]
I can spend some time to try to fix it. Any ideas which files to start looking at?

**Comment by dcarroll** [comment]
It's a little tricky.  I confirmed that the zip file being pushed contains
a package.xml file.  In the metadata.go DeployZipFile func you can
uncomment out the first line of code and the zip file will be written to
and left on disk at the same level as the metadata folder.

You could confirm that in your environment as well.

On Mon, Jul 6, 2015 at 10:30 AM, Alex Berg <notifications@github.com> wrote:

> I can spend some time to try to fix it. Any ideas which files to start
> looking at?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/186#issuecomment-118932930>.
>



-- 
Thanks,
Dave

**Comment by dcarroll** [comment]
Kind of stumped by this.  I took the generated package.zip file and fed it into workbench.developerforce.com, using v33.0 on workbench (there is a missing deployOptions header that was introduced in v34.0), and successfully created/updated a Visualforce Page.  I've compared the SOAP that is generated both on the Mac and Windows. Aside from CR/LF vs just LF there are only some small differences in the base64 representation of the package.zip file.

To investigate further, I'm going to have to temporarily add a flag to accept a zip file on the command line, and package up the Mac zip into the SOAP and see if that works. Even if it does, I'm not sure what good it will do.

Stay tuned.

**Comment by chexxor** [comment]
You said that the package.xml is in the "metadata" directory which contains the files. Here's the package.xml in there.

```
<?xml version=<members>1.0<members> encoding=<members>UTF-8<members>?>
<Package xmlns=<members>http://soap.sforce.com/2006/04/metadata<members>>
	<types>
		...
		<name>ApexClass</name>
	</types>
	<types>
		...
		<name>ApexComponent</name>
	</types>
	<types>
		...
		<name>ApexPage</name>
	</types>
	<types>
		...
		<name>ApexTrigger</name>
	</types>
	<types>
		...
		<name>CustomField</name>
	</types>
	<types>
		...
		<name>CustomObject</name>
	</types>
	<types>
		...
		<name>StaticResource</name>
	</types>
	<types>
		...
		<name>WebLink</name>
	</types>
	<version>33.0</version>
</Package>
```

Notice the thing in the `xmlns` attribute? Maybe that's the problem. :-/

**Comment by dcarroll** [comment]
Where did that package.xml come from?
How was it generated?  By the cli, or some other way?

On Mon, Jul 6, 2015 at 4:07 PM, Alex Berg <notifications@github.com> wrote:

> You said that the package.xml is in the "metadata" directory which
> contains the files. Here's the package.xml in there.
>
> <?xml version=<members>1.0<members> encoding=<members>UTF-8<members>?>
> <Package xmlns=<members>http://soap.sforce.com/2006/04/metadata<members>>
>     <types>
>         ...
>         <name>ApexClass</name>
>     </types>
>     <types>
>         ...
>         <name>ApexComponent</name>
>     </types>
>     <types>
>         ...
>         <name>ApexPage</name>
>     </types>
>     <types>
>         ...
>         <name>ApexTrigger</name>
>     </types>
>     <types>
>         ...
>         <name>CustomField</name>
>     </types>
>     <types>
>         ...
>         <name>CustomObject</name>
>     </types>
>     <types>
>         ...
>         <name>StaticResource</name>
>     </types>
>     <types>
>         ...
>         <name>WebLink</name>
>     </types>
>     <version>33.0</version>
> </Package>
>
> Notice the thing in the xmlns attribute? Maybe that's the problem. :-/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/186#issuecomment-119023861>.
>



-- 
Thanks,
Dave

**Comment by dcarroll** [comment]
So, I definitely think that it's the zip file that is generated. The package.xml is also generated on fly based on the arguments for the push command.  I was able to create the zip file, including the package.xml on my Mac and modified the push command to just take a path to a zip and wrap in the SOAP deploy wrapper.  First tried the generated zip from windows and failed, then tried the Mac generated zip and succeeded.  

Not sure where to go from here.  The zip file is not entirely corrupt as it can be unzipped anywhere.  Happy to entertain any and all suggestions at this point.

**Comment by cwarden** [comment]
The zip file was being created with backslashes:

```
$ unzip -l package.zip
Archive:  package.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
      225  00-00-1980 00:00   unpackaged\package.xml
    74756  00-00-1980 00:00   unpackaged\pages/Test.page
      283  00-00-1980 00:00   unpackaged\pages/Test.page-meta.xml
---------                     -------
    75264                     3 files
```

I opened #187 to always uses a forward slash, which the [archive/zip](http://golang.org/pkg/archive/zip/#Writer.Create) docs say is required.

**Comment by dcarroll** [comment]
Great!  RTFM!!

Thanks Christian.

On Tue, Jul 7, 2015 at 9:57 AM, Christian G. Warden <
notifications@github.com> wrote:

> The zip file was being created with backslashes:
>
> $ unzip -l package.zip
> Archive:  package.zip
>   Length      Date    Time    Name
> ---------  ---------- -----   ----
>       225  00-00-1980 00:00   unpackaged\package.xml
>     74756  00-00-1980 00:00   unpackaged\pages/Test.page
>       283  00-00-1980 00:00   unpackaged\pages/Test.page-meta.xml
> ---------                     -------
>     75264                     3 files
>
> I opened #187 <https://github.com/heroku/force/pull/187> to always uses a
> forward slash, which the archive/zip
> <http://golang.org/pkg/archive/zip/#Writer.Create> docs say is required.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/186#issuecomment-119267334>.
>



-- 
Thanks,
Dave

**Comment by chexxor** [comment]
Did this patch get built into the binary linked in the README? I am still getting an error

```
Failures - 1                                
ERROR with package.xml, line 0              
 No package.xml found                       
```

**Comment by chexxor** [comment]
I see a new release hasn't been made yet, so it's likely that the binaries in the README aren't updated. I'll try to build from source and use that binary this weekend.

**Comment by cwarden** [comment]
Here's the windows binary I built if you want to try it: https://gist.github.com/cwarden/103e283665ba52c61399

**Comment by dcarroll** [comment]
I'll push a release this afternoon.

**Comment by dcarroll** [comment]
Ok, the new version has been published, you pull request should now be in the binary.

**Comment by chexxor** [comment]
Sick! The new binary works! Thanks! And thanks to @cwarden for the fix!
