### ISSUE TITLE
Support of "URL" field type

### ISSUE THREAD

**Issue by Timur-P** [heroku/force#205]
As I understand it is not supported now. At least, "force field type" does not list it.
Can it be supported?

**Comment by dcarroll** [comment]
It's just an omission.  Have you tried to use it?

**Comment by Timur-P** [comment]
I'm new to it, I've just tried

**Comment by dcarroll** [comment]
Ok, I'll take a look, should be easy to add.

**Comment by Timur-P** [comment]
Thanks a lot

**Comment by jpmonette** [comment]
@dcarroll Should this be closed?

**Comment by dcarroll** [comment]
Yup, thanks!

On Wed, Oct 21, 2015 at 3:05 PM, Jean-Philippe Monette <
notifications@github.com> wrote:

> @dcarroll <https://github.com/dcarroll> Should this be closed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/205#issuecomment-150038139>.
>



-- 
Thanks,
Dave

**Comment by Timur-P** [comment]
Hm... I've installed "go" (on windows), run "go get -u github.com/heroku/force", got the "force.exe" in bin folder in GOPATH folder, and still 
force field type Url
force field type url
force field type URL
    all resulted in "Sorry, that is not a valid field type"
What am I doing wrong?

**Comment by Timur-P** [comment]
I've checked the changes in your commit in metadata.go - they all are on my harddrive, so probably they do not work?

**Comment by Timur-P** [comment]
Also, I've noticed that in ValidateFieldOptions function here
	case "picklist":
		attrs = getAttributes(&PicklistField{})
		s = reflect.ValueOf(&PicklistFieldRequired{}).Elem()
	case "phone":
		attrs = getAttributes(&PhoneField{})
		s = reflect.ValueOf(&PhoneFieldRequired{}).Elem()
		break
probably should be "break" after picklist. 
Sorry I'm new to open source projects, not sure how to fix it by myself

**Comment by Timur-P** [comment]
In fact, the problem is in func DisplayFieldDetails(fieldType string) - it does not have "case" for url.

**Comment by Timur-P** [comment]
You have changed it as well, but your pull request did not make it (it is #209 and marked with error).

**Comment by Timur-P** [comment]
>Sorry I'm new to open source projects, not sure how to fix it by myself

I have changed it and created pull request
