### ISSUE TITLE
Unable to download the windows Force CLI binaries

### ISSUE THREAD

**Issue by rickvannierop** [heroku/force#214]
Going to: https://godist-new.herokuapp.com/projects/heroku/force/releases/current/windows-amd64/force.exe results in an internal server error.

**Comment by dcarroll** [comment]
Working on it. In the mean time you can get it from here.

https://s3-us-west-2.amazonaws.com/force-cli/heroku/force/0.22.36/windows-amd64/force.exe
https://s3-us-west-2.amazonaws.com/force-cli/heroku/force/0.22.36/windows-386/force.exe

On Wed, Nov 4, 2015 at 6:36 AM, Rick van Nierop <notifications@github.com>
wrote:

> Going to:
> https://godist-new.herokuapp.com/projects/heroku/force/releases/current/windows-amd64/force.exe
> results in an internal server error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/214>.
>



-- 
Thanks,
Dave

**Comment by dcarroll** [comment]
Ok, I've replaced couchdb with mongodb as the backing store for godist-new.  Should be working as expected.
