### ISSUE TITLE
Login Failing

### ISSUE THREAD

**Issue by stefangoor** [heroku/force#253]
Hi,

We have been using the login functionality as part of a nightly build / CI process for a long time and it has worked well for us, however last night it failed in all our builds with the following error:

Cannot GET /auth/soaplogin/?id=https://na17.salesforce.com/id/{someid}/{someid}&amp;access_token={sometoken}&amp;instance_url=https://na17.salesforce.com
ERROR: Cannot GET /auth/soaplogin/?id=https://na17.salesforce.com/id/{someid}/{someid}&amp;access_token={sometoken}&amp;instance_url=https://na17.salesforce.com

I have replaced the ids and tokens with {..}.

Do you know why this would be failing now?

Thanks,
Stefan

**Comment by CzarScar** [comment]
We also met this issue while login into sandbox with correct username, password and security token.
Just wonder to know if this is an issue of force.com CLI or Salesforce platform problem?

Thank you very much.

**Comment by mattgoldspink** [comment]
We're also facing this issue - Taking a look through the code it seems to be an issue when trying to do a GET to a server hosted on 

https://force-cli.herokuapp.com/auth/soaplogin

**Comment by tggagne** [comment]
We, too, are getting the bug.  We did nothing to the force program, so I imagine it's something on SF's end.  Trust.salesforce.com isn't showing any problems (for cs4).  

So the question is, how do such things get reported?

BTW:  the GET error URL looks to be poorly formed.  Why would it start with /auth/soaplogin/ when it should start with a domain, like, 's4.salesforce.com/auth/soaplogin' or something similar?

**Comment by dcarroll** [comment]
I'm going to do a rollback to a build of the login logging server that was pushed yesterday. Sorry for the inconvenience .

Dave Carroll

**Comment by dsipasseuth** [comment]
IMHO, it should not connect to https://force-cli.herokuapp.com in the first place. 
Login to SalesForce using the SOAP endpoint does not need it AFAIK.

It seems to send a **valid** access token and instance url back to a hosted service via a GET request... 

Commenting / Removing out few lines in force.go (372 to 380) seems to make the problem go away...

**Comment by wbushey** [comment]
We're having this problem, and did the same thing as @dsipasseuth, which raises the question of why force-cli.herokuapp.com needs to be involved at all. Could force.com-cli just start it's own webserver to host a callback URL?

**Comment by dcarroll** [comment]
The login should be working now.  The connection to force-cli.herokuapp.com is used to count logins via the CLI.  This is an important metric in my on-going efforts to get the CLI to be a supported tool much like the Java WSC client.  There are also security implications of trying to make the call back to a CLI launched localhost when using OAuth to authenticate.

**Comment by stefangoor** [comment]
great work! Thanks for the quick fix :)

**Comment by dcarroll** [comment]
Sorry for the issue.  The reason why it was a quick fix is because I am
using Heroku Pipelines <https://devcenter.heroku.com/articles/pipelines> to
easily manage the promotion and demotion to and from production.  Just
implemented this in anticipation of the changes that were due just in case
this situation occurred.

On Wed, Feb 3, 2016 at 8:15 AM, stefangoor <notifications@github.com> wrote:

> great work! Thanks for the quick fix :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/253#issuecomment-179318788>.
>



-- 
Thanks,
Dave

**Comment by tggagne** [comment]
Works for me.  Merci beaucoup!

**Comment by wbushey** [comment]
Same for me. Thank you.

**Comment by cwarden** [comment]
The dependency on the heroku app has been bugging me.  8849f8752e3492936b4a1dfea4eb068be2e352bb removes that dependency by using a callback url on localhost.  (It works essentially the same was as @kevinohara80's dmc, even borrowing it's html page.)

It also adds support for refreshing the session token upon expiration if you authenticate using OAuth.  Testing of this functionality would be appreciated.

Now, @dcarroll points out a legitimate reason for the heroku app, in tracking application usage, but it seems like this would better be done through reporting on the Connected App.  Unfortunately, I haven't found anywhere that usage of a Connected App is reported to the creator of the Connected App.  Usage only seems to be reported within each org that has users of the Connected App.  Have I overlooked something?  Does Salesforce expose this data internally in a way that would be sufficient for trying to garner internal developer support?

**Comment by CzarScar** [comment]
Thank you for the quick fix. Works fine now.

**Comment by kevinohara80** [comment]
If the issue is just tracking logins, all you'd need to implement is a post-login hook to some analytics backend.

**Comment by dsipasseuth** [comment]
I think this callback should just be removed.

They are other means (already implemented in the command line) for getting metrics...

Should i create a new issue for this ?

**Comment by cwarden** [comment]
I've been running my branch which adds session refresh and removes the dependency on the Heroku app for a couple weeks.

I added back logging to the heroku endpoint for usage tracking, but it no longer sends the session token or any identifying information.  And if it fails, it doesn't prevent the application from working.

@dcarroll, what do you think about merging f5c35082c7d9486f3e89ebf04c4ca565488ff8bc?

**Comment by dcarroll** [comment]
Sorry, putting out fires today.  I'll take a look tomorrow.
