### ISSUE TITLE
force login does not work post v0.22.33

### ISSUE THREAD

**Issue by thhsfdc** [heroku/force#262]
running v0.22.51:

```
force login -u=thoeger.sfdc@dx.roche.com.pacmandev -i=https://rexis--PacmanDev.cs87.my.salesforce.com -p=*****
Loaded Endpoint: (https://thh9d--FULL.cs10.my.salesforce.com)
ERROR: INVALID_LOGIN: Invalid username, password, security token; or user locked out.
```

==> retrieves the end point used with a previous login

--------
crosschecking with v0.22.33 I can execute this:
```
force33 login -u=thoeger.sfdc@dx.roche.com.pacmandev -i=https://rexis--PacmanDev.cs87.my.salesforce.com -p=*******
Loaded Endpoint: (https://rexis--PacmanDev.cs87.my.salesforce.com)
Save login was  ok
Logged in as 'thoeger.sfdc@dx.roche.com.pacmandev'
```
==> this works as expected

**Comment by cwarden** [comment]
Looks like it was broken in b56e57d3ade398f010f338b78baef1a15f6433e6.  The logic for reusing the last endpoint doesn't seem to work.  @ViViDboarder, shouldn't the previous endpoint only be used if the `-i` argument isn't set?

**Comment by dcarroll** [comment]
That seems like a good approach.

On Fri, Feb 26, 2016 at 8:01 AM, Christian G. Warden <
notifications@github.com> wrote:

> Looks like it was broken in b56e57d
> <https://github.com/heroku/force/commit/b56e57d3ade398f010f338b78baef1a15f6433e6>.
> The logic for reusing the last endpoint doesn't seem to work.
> @ViViDboarder <https://github.com/ViViDboarder>, shouldn't the previous
> endpoint only be used if the -i argument isn't set?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/262#issuecomment-189340073>.
>



-- 
Thanks,
Dave

**Comment by ViViDboarder** [comment]
Yea, that was the intended interface. It works for me to specify `-i login` when my default is `test`.

When I do the same, command it shows the passed in url.

I get the following:

```
force (master)$ force login -u=foo@bar.com.pacmandev -i=https://rexis--PacmanDev.cs87.my.salesforce.com -p=foo
Loaded Endpoint: (https://rexis--PacmanDev.cs87.my.salesforce.com)
ERROR: INVALID_LOGIN: Invalid username, password, security token; or user locked out.
```

And my "default" is `https://test.salesforce.com/`

**Comment by ViViDboarder** [comment]
Maybe there's an issue when the last successful one was a custom endpoint... I'll investigate

**Comment by ViViDboarder** [comment]
And I think I see the issue... The previous custom endpoint is loaded and set here: https://github.com/heroku/force/blob/master/login.go#L44

Which is fine with `-i test` or `-i login` because it isn't used, but when not using either of those, it will check `*instance`, which is overwritten already. It should move to the default method and be done if `*instance` is empty instead.
