### ISSUE TITLE
Support for Global Picklists in Metadata import & export

### ISSUE THREAD

**Issue by orospakr** [heroku/force#277]
Thank you!

**Comment by cwarden** [comment]
Where are global picklists stored?  I see the `globalPicklist` tag in the object metadata, which references a global picklist by name, but I couldn't find where the picklists themselves are managed in the docs.

**Comment by dcarroll** [comment]
Global Picklist is not available until API v37.0, Summer release.

**Comment by dcarroll** [comment]
Just tested on a pre-release version of v37.0, works as exepected
`
force describe -t metadata -n GlobalPicklist
force fetch -t GlobalPicklist -n TestGlobalPL
`
