### ISSUE TITLE
Ability to specify API version number

### ISSUE THREAD

**Issue by orospakr** [heroku/force#278]
Hey, the code seems to hardcoded API 34, but I'm trying to use it with an organisation of API 36, particularly deploying some metadata that refers to some API 36 features.

Thank you!

**Comment by dcarroll** [comment]
I just release a version that allows setting of the API version
To view the currently set version:
`
force apiversion
`
To set the version:
`
force apiversion v36.0
`

**Comment by orospakr** [comment]
wow, thank you for the amazing turn-around time!
