### ISSUE TITLE
Force CLI doesn't properly escape file paths, e.g., with spaces in folder names

### ISSUE THREAD

**Issue by alderete-sfdc** [heroku/force#284]
When saving changes back to a Lightning app resource, using the Sublime Lightning plugin, the Sublime console opens and reports the following:

```
stat /Users/malderete/Development/Universal: no such file or directory
ERROR: File does not exist
/Users/malderete/Development/Universal
[Finished in 0.1s with exit code 1]
[cmd: ['force', 'aura', 'push -f=/Users/malderete/Development/Universal Samples/202_blitz04/metadata/aura/ExpenseTracker3/ExpenseTracker3.app']]
[dir: /Users/malderete/Development/Universal Samples/202_blitz04/metadata/aura/ExpenseTracker3]
[path: ~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin]
```

Pretty clear that the directory path isn't being escaped, and the space in "Universal Samples" is causing it to have problems.

And, when I remove the space from the directory name, the save operation once again works just fine.

I'd call this one important. A file path escaping bug is what caused Apple to wipe out people's hard drives in an iTunes installer, many years ago. We don't want to do that.

Interestingly, before trying to save changes, I was able to fetch metadata from my org just fine. I wonder what the difference is, where the spaces in the directory name didn't affect it?

**Comment by dcarroll** [comment]
The fetch is likely using relative paths. ???

On Fri, May 6, 2016 at 5:14 AM, Michael Alderete <notifications@github.com>
wrote:

> When saving changes back to a Lightning app resource, using the Sublime
> Lightning plugin, the Sublime console opens and reports the following:
>
> stat /Users/malderete/Development/Universal: no such file or directory
> ERROR: File does not exist
> /Users/malderete/Development/Universal
> [Finished in 0.1s with exit code 1]
> [cmd: ['force', 'aura', 'push -f=/Users/malderete/Development/Universal Samples/202_blitz04/metadata/aura/ExpenseTracker3/ExpenseTracker3.app']]
> [dir: /Users/malderete/Development/Universal Samples/202_blitz04/metadata/aura/ExpenseTracker3]
> [path: ~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin]
>
> Pretty clear that the directory path isn't being escaped, and the space in
> "Universal Samples" is causing it to have problems.
>
> And, when I remove the space from the directory name, the save operation
> once again works just fine.
>
> I'd call this one important. A file path escaping bug is what caused Apple
> to wipe out people's hard drives in an iTunes installer, many years ago. We
> don't want to do that.
>
> Interestingly, before trying to save changes, I was able to fetch metadata
> from my org just fine. I wonder what the difference is, where the spaces in
> the directory name didn't affect it?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/284>
>



-- 
Thanks,
Dave

**Comment by dcarroll** [comment]
To get the updated fix you will need to update the Sublime Plugin to 1.2.15 AND the Force CLI, version v0.22.57.
