### ISSUE TITLE
Not working on Wndows 10

### ISSUE THREAD

**Issue by aj2taylo** [heroku/force#295]
I downloaded this from http://force-cli.herokuapp.com/, but when I open up a cmd prompt and enter "force login", I get "'force' is not recognized as an internal or external command, operable program or batch file".

Any thoughts?

**Comment by dcarroll** [comment]
Due to lack of installer and inability to have the downloaded file be marked as executable, you need to either use force.exe for windows or create a shortcut to force.exe and ensure the shortcut is in your path so that it can be executed from any path in the command window.
