### ISSUE TITLE
can not login: `Application error`

### ISSUE THREAD

**Issue by vitaly-zdanevich** [heroku/force#314]
![screen shot 2016-10-07 at 11 19 03](https://cloud.githubusercontent.com/assets/3514015/19183207/e785a454-8c7f-11e6-88d1-de75e6ae2fb6.png)

**Comment by thegogz** [comment]
See #270

**Comment by dcarroll** [comment]
Yes, can you look at the url for the oauth callback in that browser tab?

**Comment by vitaly-zdanevich** [comment]
now I can
