### ISSUE TITLE
go get -u github.com/heroku/force throws Error

### ISSUE THREAD

**Issue by john-benson** [heroku/force#329]
go get -u github.com/heroku/force causes:

# github.com/heroku/force
../src/github.com/heroku/force/force.go:633: dec.Token  (type *json.Decoder has no field or method Token)
../src/github.com/heroku/force/force.go:650: dec.Token undefined (type *json.Decoder has no field or method Token)
../src/github.com/heroku/force/force.go:654: dec.Token undefined (type *json.Decoder has no field or method Token)
../src/github.com/heroku/force/force.go:658: dec.Token undefined (type *json.Decoder has no field or method Token)
../src/github.com/heroku/force/force.go:697: dec.Token undefined (type *json.Decoder has no field or method Token)
../src/github.com/heroku/force/force.go:709: dec.Token undefined (type *json.Decoder has no field or method Token)
../src/github.com/heroku/force/force.go:716: dec.Token undefined (type *json.Decoder has no field or method Token)
../src/github.com/heroku/force/force.go:718: dec.Token undefined (type *json.Decoder has no field or method Token)
../src/github.com/heroku/force/force.go:728: dec.Token undefined (type *json.Decoder has no field or method Token)
../src/github.com/heroku/force/force.go:745: dec.Token undefined (type *json.Decoder has no field or method Token)
../src/github.com/heroku/force/force.go:745: too many errors

**Comment by deanmorin** [comment]
I'm getting the same error, what was the resolution here?

**Comment by john-benson** [comment]
Hey dean,

Sorry I didn't respond with my fix. I needed up grade my go version. This
did cause another issue however that I do not believe is resolved.

John
