### ISSUE TITLE
Query breaks when `\n` in text field

### ISSUE THREAD

**Issue by deanmorin** [heroku/force#345]
I have a text field (`next_actions__c`) with the following text:

```
intro not complete
\need 2015 pbtr
df
jan bank
```

The `\n` seems to throw everything for a loop when running a csv query.

I run this command:

```
force query "SELECT id, next_actions__c, withdrawn_reason__c FROM opportunity WHERE id = '0061a00000G6f7uAAB'" --format:csv > /tmp/out.csv
```

This results in this file (carriage returns shown as `^M`):

```
"Id","Next_Actions__c","Withdrawn_Reason__c"
"0061a00000G6f7uAAB","intro not complete^M
","<nil>              "
"  ","eed 2015 pbtr^M
df^M
jan bank","                   "

```

**Comment by dcarroll** [comment]
Thanks for this issue and the clear use case for reproduction.  Will take a look at what we can do.

**Comment by dcarroll** [comment]
Hey Dean, I actually can't reproduce this on my mac. Are you on windows?

**Comment by deanmorin** [comment]
Oops, my bad I wasn't running the latest version of force. Look like this was fixed somewhere along the way. Thanks for the quick response though, and a very handy tool!

**Comment by dcarroll** [comment]
No worries! Thanks for you support!

![image](https://cloud.githubusercontent.com/assets/116254/20366364/9df513b6-abff-11e6-94fc-ad45b4271726.png)
