### ISSUE TITLE
Setting `force apiversion` does not appear to persist

### ISSUE THREAD

**Issue by ImJohnMDaniel** [heroku/force#347]
When executing ...

> force apiversion 36.0

...the change does not appear to persist.  After executing the above command and then run the basic command to check apiversion, the response still comes back as v37.0.

Using v0.22.60 for MacOS 64bit on MacOS 10.12.1

**Comment by dcarroll** [comment]
You need to be logged in.  The version is saved in a "dot" file and associated with the currently active login.

**Comment by ImJohnMDaniel** [comment]
I am logged in.  `Force active` does show an active login

**Comment by dcarroll** [comment]
can you try logging in again?

**Comment by ImJohnMDaniel** [comment]
@dcarroll very weird.  Logging out and logging back in worked.

Why would it show that I was still logged in then ...prior to me logging out just now?
