### ISSUE TITLE
`force export` fail when "Insights" type folder exists.

### ISSUE THREAD

**Issue by tarot** [heroku/force#352]
When `force export`, I encountered an error:

```
$ force export
DeveloperName, Folder.DeveloperName from Insights
                                         ^
ERROR at Row:1:Column:53
sObject type 'Insights' is not supported. If you are attempting to use a custom object, be sure to append the '__c' after the entity name. Please reference your WSDL or the describe call for the appropriate names.
```

Some orgs return Folder record that Type is "Insights".
Then, this query will be `SELECT Id, DeveloperName, Folder.DeveloperName from Insights`.
https://github.com/heroku/force/blob/95f3519744e176e8cc23bc55ceacb4781817ad38/export.go#L32
But sObject type "Insights" is not supported. So `force export` fail.

This query might be `SELECT Id, Type, DeveloperName from Folder where Type in ('Dashboard', 'Document', 'Email', 'Report')`.
https://github.com/heroku/force/blob/95f3519744e176e8cc23bc55ceacb4781817ad38/export.go#L169

I don't know why "Insights" type folder exists, and what "Insights" type means. It's undocumented.
https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_folder.htm

**Comment by jkentjnr** [comment]
+1 Same issue.

**Comment by tarot** [comment]
I had overlooked the fix.
