### ISSUE TITLE
Can't log in with Windows Subsystem Linux (WSL)

### ISSUE THREAD

**Issue by synle** [heroku/force#396]
I know this is quite an edge case, but currently we can't login using windows bash. Is this on the road map for support?

If not supported, is there a known workaround to get this working?

When I tried `force login`, it just hanged.

![2017-04-01 10_25_23-bash on ubuntu on windows](https://cloud.githubusercontent.com/assets/3792401/24580896/918106ea-16c5-11e7-908e-33208f0a3415.png)

I was able to get a little further using `-u` and `-p`, but got the following error message:

`ERROR: LOGIN_MUST_USE_SECURITY_TOKEN: Invalid username, password, security token; or user locked out. Are you at a new location? When accessing Salesforce--either via a desktop client or the API--from outside of your company’s trusted networks, you must add a security token to your password to log in. To get your new security token, log in to Salesforce. From your personal settings, enter Reset My Security Token in the Quick Find box, then select Reset My Security Token.
`

**Comment by synle** [comment]
I gave up on trying to get it worked. Figured out a workaround.

Used force from Windows, then using Ubuntu interpolation to proxy the command to windows subsystem which works now.

The only thing is that this change doesn't make it to public version yet, will soon be.

Refer to this doc for the feature I used.
https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-14951

**Comment by morriswinkler-simplesurance** [comment]
I got a similar problem on a server, my solution is to log into salesforece on my my desktop machine and then run.

`
scp -r ../../.force server:
`
