### ISSUE TITLE
Problem with compiling tool from source 

### ISSUE THREAD

**Issue by yurybond** [heroku/force#408]
When run 

` go get -u github.com/heroku/force`

get the following exceptions

> go: missing Mercurial command. See https://golang.org/s/gogetcmd
> package bitbucket.org/pkg/inflect: exec: "hg": executable file not found in %PATH%

**Comment by yurybond** [comment]
I had missing package for Mercurial. Can be found here - https://www.mercurial-scm.org/downloads

It would be nice to have some info in documentation about this pre-requisite.

**Comment by dcarroll** [comment]
That is a golang thing not specific to the CLI
