### ISSUE TITLE
Support for API v40.0

### ISSUE THREAD

**Issue by mick-mehigan** [heroku/force#427]
Working with version `v0.22.73`, I'm getting two errors when doing a
```
$ force push -f apexFile
```
1. [APEX] Error Method does not exist or incorrect signature: void publish(SObject) from the type EventBus
2. [OBJECT]Error Property 'enableChangeDataCapture' not valid in version 39.0

**Comment by dcarroll** [comment]
Try setting the api version to v40.0

**Comment by mick-mehigan** [comment]
https://github.com/heroku/force/releases/tag/v0.22.73 did update the api version to v40.0, did it not?

**Comment by dcarroll** [comment]
Yes, but based on the message it looks like it is set locally to v39.0

**Comment by mick-mehigan** [comment]
where can I check that?

```
$ force apiversion
```
returns `v40.0`

the meta data of the class being put to Org has
```
<apiVersion>40.0</apiVersion>
```

**Comment by dcarroll** [comment]
Then I wonder why it says v39.0 in the error message?

**Comment by mick-mehigan** [comment]
I created a new Org, and force pushed those two classes, this time with success.
