### ISSUE TITLE
Force.com CLI Download Faile

### ISSUE THREAD

**Issue by brettphillips05** [heroku/force#447]
[CLI Home Page](http://force-cli.herokuapp.com/) link does not link to a working executable. When I try to download the Windows version, I am [directed to a broken link](https://godist-new.herokuapp.com/projects/heroku/force/releases/current/windows-amd64/force.exe). I had the same response checking other platform executables.
 
I  was able to download from the [latest release](https://github.com/heroku/force/releases/latest) page on GitHub.

**Comment by dcarroll** [comment]
Added redirect to https://developer.salesforce.com/tools/forcecli.
