### ISSUE TITLE
Rest command is not working

### ISSUE THREAD

**Issue by dirajkumar** [heroku/force#450]
![rest_command 1](https://user-images.githubusercontent.com/1153390/31192159-6c03a752-a90e-11e7-8652-3e453ff717cd.gif)

**Comment by cwarden** [comment]
This was fixed in #448.

**Comment by dirajkumar** [comment]
Okay. Can I run force update to get the newest version or download and replace the old file?

**Comment by dcarroll** [comment]
No, unfortunately.  Update is not implemented.  You will need to download it from here.

https://developer.salesforce.com/tools/forcecli

**Comment by dirajkumar** [comment]
Still same result. I downloaded and replaced the force.

**Comment by cwarden** [comment]
The fix will be in the next release.  If you build from source, it's on the master branch.

**Comment by dcarroll** [comment]
I'll cut a new release now, was waiting for some CI stuff to finish.

**Comment by dcarroll** [comment]
Give it about 20 minutes and download again.  You will now the download is ready when you see the release pages has 8 downloadable resources.
