### ISSUE TITLE
Le CLI home page is down

### ISSUE THREAD

**Issue by tiflopin** [heroku/force#456]
In the README, the CLI Home Page link http://force-cli.herokuapp.com/ is down.

**Comment by dcarroll** [comment]
Might have been temporarily down. It is up now.

**Comment by tiflopin** [comment]
Oh I still get "Application error".

**Comment by dcarroll** [comment]
Huh.  Maybe there is a caching issue with your (or my) browser?  I'll take
another look.

**Comment by tiflopin** [comment]
No. May be its is because i'm in France ?

**Comment by dcarroll** [comment]
Oh,  I didn't notice the /fr/. Remove that and try again.

It could be a bug on developer.salesforce.com

**Comment by tiflopin** [comment]
Cool ! It works again from my computer.
I think you're right it was a bug on developer.salesforce.com
I thought you could act on developer.salesforce.com :-)



2017-10-21 20:56 GMT+02:00 Dave Carroll <notifications@github.com>:
